# docker-compose.yml
services:
  poke-client:
    container_name: poke-client
    env_file:
     - .env
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT}:5173" 
    volumes:
      - ./client:/app 
      - /app/node_modules 
    networks:
      - pokedex-net

  poke-server:
    container_name: poke-server
    env_file:
     - .env
    build:
      context: ./server
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - poke-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - pokedex-net

  poke-db:
    container_name: poke-db
    env_file:
     - .env
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "${DATA_DIR}/pgdata:/var/lib/postgresql/data"
    networks:
      - pokedex-net

networks:
  pokedex-net:
    driver: bridge